### ISSUE TITLE
Narrowed types are not merged at join points after an `if` statement

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#44755]
### Description

Narrowed types are not merged where control flow joins after an `if` statement. When every path reaching a statement narrows a variable, the compiler still uses the variable's declared type.

### Steps to Reproduce

```ballerina
function f(int|boolean|float x, boolean b) returns int|boolean {
    if b {
        if x is float {
            return true;
        }
        // x is int|boolean here
    } else {
        return 0;
    }
    return x;
}
```

### Current Behavior

```
ERROR [main.bal:(10:12,10:13)] incompatible types: expected '(int|boolean)', found '(int|boolean|float)'
```

### Expected Behavior

Compiles. `return x` is reachable only by falling out of the `if` body, where `x` was narrowed to `int|boolean`; the `else` returns. The narrowed type at the join is the union of the incoming paths.

### Affected Versions

Fails on 2201.13.2, 2201.13.4, 2201.13.6 and 2201.14.0-alpha.

### Regression in a related shape

Where the narrowing happened to be applied before, it is now lost. This compiles with 2201.13.2 and 2201.13.4, and fails from 2201.13.6:

```ballerina
function get() returns int|boolean|float => 1.0;

function g(boolean b) returns int|boolean {
    int|boolean|float x = get();
    if x is float {
        if b {
            x = get();
            if x is float {
                return true;
            }
        } else {
            return 0;
        }
    }
    return x;
}
```

Here the narrowing previously came from the completion-status analysis treating the outer `if` as non-completing, so falsity narrowing was applied to the following statements. #44692 (specifically 2f8ae256705, removing the rule that propagated the true-branch's completion status when the else completes normally) corrected that analysis, which looks right on its own, but with no union at the join the narrowing is lost instead.

Taking the union of the falsity type and the type at the body's normal exit would keep `test37` in `test_type_guard_type_narrow_3.bal` an error, since its fall-through leaves the variable unnarrowed.

**Comment by manuranga** [comment]
Blocker for ICP

**Comment by Thevakumar-Luheerathan** [comment]
@senuriwick can you update an ETA for this?

**Comment by Thevakumar-Luheerathan** [comment]
@senuriwick can you send the same fix for the 2201.14.x, master as well??

**Comment by chiranSachintha** [comment]
This PR(https://github.com/ballerina-platform/ballerina-lang/pull/44764) will fix this issue along with some other type-narrowing issues.
