### ISSUE TITLE
Cannot cast a single byte to string

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#9809]
**Description:**
It is not possible to cast a single byte to a string

**Steps to reproduce:**
```ballerina
byte val = 1;
string text = <string>val;
```
gives a compilation error:
`error: ./main.bal:5:19: incompatible types: 'byte' cannot be converted to 'string'`

**Affected Versions:**
0.980

**Comment by MaryamZi** [comment]
This is no longer a valid cast as per the 0.990.0 specification. It is not possible to cast a non-string value to string. 

The changes to the type cast expression were introduced with https://github.com/ballerina-platform/ballerina-lang/pull/13479.

At the moment, `io:sprintf` needs to be used to do this conversion:
```ballerina
import ballerina/io;

public function main(string... args) {
    byte val = 12;
    string text = io:sprintf("%s", val);
    io:println(text);
}
```

Refer - https://groups.google.com/d/topic/ballerina-dev/9wSEMbqkltI/discussion
