### ISSUE TITLE
BBEs for encoding are not working

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#25303]
**Description:**

The BBE for encoding [1] gives the following errors.

With Ballerina version 1.2.7
```
error: ballerina/encoding:1.0.1::/src/encoding/encoding_errors.bal:18:36: extraneous input 'error'
error: ballerina/encoding:1.0.1::/src/encoding/encoding_errors.bal:21:36: extraneous input 'error'
error: ballerina/encoding:1.0.1::/src/encoding/encoding.bal:39:62: unknown type 'Error'
error: ballerina/encoding:1.0.1::/src/encoding/encoding.bal:53:88: unknown type 'Error'
error: ballerina/encoding:1.0.1::/src/encoding/encoding.bal:67:88: unknown type 'Error'
error: dilhashanazeer/formattest:0.1.0::new.bal:14:36: incompatible types: expected '(byte[]|error)', found '(byte[]|other)'
error: dilhashanazeer/formattest:0.1.0::new.bal:20:19: incompatible types: expected '(string|error)', found '(string|other)'
error: dilhashanazeer/formattest:0.1.0::new.bal:25:40: incompatible types: expected '(string|error)', found '(string|other)'

```
With Ballerina version slp3

Crashes with below error

```
SEVERE {b7a.log.crash} - org/ballerinalang/jvm/values/ArrayValue 
java.lang.NoClassDefFoundError: org/ballerinalang/jvm/values/ArrayValue
```

[1] https://ballerina.io/swan-lake/learn/by-example/url-encode-decode.html

There is no difference in the BBE for the above versions.

**Steps to reproduce:**

Try BBE for encoding with Ballerina 1.2.7 and slp3.

**Affected Versions:**
Ballerina 1.2.7, slp3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
encoding 1.0.1 version should not work with ballerina 1.2.7 release. We should not allow to pull this version when the user running on ballerina 1.2.x releases. 
For slp3 issue, may be related to the issue #25309

**Comment by Dilhasha** [comment]
The problem is, the example shows the same code for both 1.2.7 and slp3. So, according to my understanding the code sample needs to be corrected for 1.2.7 to use the 1.0.0 encoding module.
