### ISSUE TITLE
Error while returning an empty array from inside query action

### ISSUE THREAD

**Issue by aadiboii** [ballerina-platform/ballerina-lang#36480]
**Description:**

I'm using check query statement to go over messages in `stream<gmail:Message, error?> msgList` and push the message IDs to a `string[]`. If the query expression encounters the same ID as stored in `string|error lastSavedMessageId` from when the script ran the last time. It should return the `string[]` array. Else continue pushing the IDs to the array. 
```
import ballerinax/googleapis.gmail;
import ballerina/io;

gmail:Client gmailClient = check new ({
    auth: {
        refreshUrl: gmail:REFRESH_URL,
        refreshToken: "",
        clientId: "",
        clientSecret: "",
        credentialBearer: "POST_BODY_BEARER",
        clientConfig: {httpVersion: "HTTP_1_1"}
    }
});


function CheckForNewMail() returns string[]|error {
    string[] newMail = [];

    string filePath = "./lastMessageId.txt";
    string|error lastSavedMessageId = io:fileReadString(filePath);

    if lastSavedMessageId is error{
        check io:fileWriteString(filePath,"");
    }

    string[] labelsToMatch = [<LABEL_ID>];
    gmail:MsgSearchFilter searchFilter = {includeSpamTrash: false, labelIds: labelsToMatch};
    stream<gmail:Message, error?> msgList = check  gmailClient->listMessages(filter = searchFilter);

    check from gmail:Message msg in msgList
        //io:println(msg);
        do {
            if (lastSavedMessageId == msg.id) {
                io:println("In If, Id: ",msg.id.toString());
                return newMail;
            }
            else {
                io:println("In Else, Id: ",msg.id.toString());
                newMail.push(msg.id.toString());
                check io:fileWriteString(filePath, newMail[0]);
    
            }
        };

     return newMail;

}

public function main() returns error?{   
    string[] newMailIds = check CheckForNewMail();
    io:println(newMailIds); 
}

```

However, if there is an ID match in the very first iteration and the `string[]` returned is empty the compiler throws the following error.
```
[2022-06-08 10:09:36,128] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.ArrayValueImpl cannot be cast to class io.ballerina.runtime.internal.values.ErrorValue (io.ballerina.runtime.internal.values.ArrayValueImpl and io.ballerina.runtime.internal.values.ErrorValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.runtime.internal.values.ArrayValueImpl cannot be cast to class io.ballerina.runtime.internal.values.ErrorValue (io.ballerina.runtime.internal.values.ArrayValueImpl and io.ballerina.runtime.internal.values.ErrorValue are in unnamed module of loader 'app')
        at aditya.testing.0.service.CheckForNewMail(service.bal:31)
        at aditya.testing.0.service.main(service.bal:50)
        at aditya.testing.0.$_init.$lambda$main$(testing)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
```
**Steps to reproduce:**
1. Populate the Gmail connector initialization with appropriate credentials and `string[] labelsToMatch` with label.
2. Run the script with the message ID saved in ./lastMessageId.txt same as the ID of the latest message in the Inbox label. 

**Affected Versions:**
Ballerina 2201.0.4 (Swan Lake)
Language specification 2022R1

**OS, DB, other environment details and versions:**
Running on VS Code web editor in Choreo

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Without the gmail client, returning empty array works fine on 2201.1.0.
```ballerina
import ballerinax/googleapis.gmail;
import ballerina/io;


function CheckForNewMail() returns string[]|error {
    string[] newMail = [];

    gmail:Message msgg = {id: "", threadId: ""};
    string lastSavedMessageId = "";
    stream<gmail:Message, error?> msgList = [msgg].toStream();

    check from gmail:Message msg in msgList
        do {
            if (lastSavedMessageId == msg.id) {
                io:println("In If, Id: ",msg.id.toString());
                return newMail;
            }
            else {
                io:println("In Else, Id: ",msg.id.toString());
                newMail.push(msg.id.toString());
            }
        };

     return newMail;

}

public function main() returns error?{   
    string[] newMailIds = check CheckForNewMail();
    io:println(newMailIds); 
}
```

@KavinduZoysa please have a look the gmail version as well

**Comment by KavinduZoysa** [comment]
More simplified example.

```ballerina
function returnErrorOrNil() returns error? {
    return ();
}

function foo() returns string|error {
    string[] strList = ["1", "2", "3", "4"];

    check from string str in strList // runtime error
    do {
        check returnErrorOrNil();
        return str;
    };
    return "";
}

public function main() returns error? {
    _ = check foo();
}
```
Runtime error:
`error: {ballerina}TypeCastError {"message":"incompatible types: 'string' cannot be cast to 'error'"}`
