### ISSUE TITLE
length() function not working for json

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-lang#17767]
**Description:**
jsonArray.length() function not working and giving the following error.

error: .::main.bal:33:5: undefined symbol 'length'

Code -
json[] jsonArray = [{ "name": "John", "age": 31 }, { "name": "Neal", "age": 22 }];
length = jsonArray.length();
io:println("JSON array size: ", length);

**Affected Versions:**
1.0.0-alpha

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Comment by MaryamZi** [comment]
This seems to be due to the `length` variable not being defined. Can you confirm if the `length` variable is defined before using it at `length = jsonArray.length();`?

The following works for me
```ballerina
import ballerina/io;

public function main(string... args) {
    json[] jsonArray = [{ "name": "John", "age": 31 }, { "name": "Neal", "age": 22 }];
    int length = jsonArray.length();
    io:println("JSON array size: ", length);
}
```

**Comment by gigara** [comment]
This is what I want to do.

//api call 
    clientEP = new("https://api.tronalddump.io/search/quote?");
    resp = clientEP->get("query=obama");

    if (resp is http:Response) {
        var payload = resp.getJsonPayload();
        if (payload is json) {
            json|error quote = payload._embedded.quotes;

            foreach json i in 0 ... quote.length()-1 {
                io:println("("+(i+1)+") "+ quote[i].value.toString());
            }
        }

Error:
error: .::main.bal:90:37: undefined function 'length'

This code worked in the 0.992 version. But not in the alpha.

**Comment by sameerajayasoma** [comment]
The type of quite is `json|error`, may be that is why it is not working.

**Comment by gigara** [comment]
Can't change the type. It gives the following error

`error: .::main.bal:71:26: incompatible types: expected 'json', found '(json|error)'`

**Comment by MaryamZi** [comment]
`.length()` is allowed only on `map<json>` or `json[]` now. 

What you can do here is first check if `quote` is a map or an array and then call `.length()` on it.

```ballerina
    if (payload is json) {
        json|error quote = payload._embedded.quotes;

        if (quote is json[]) {
            foreach int i in 0 ... quote.length()-1 {
                // operate on the array
            }
        }
    }
```

**Comment by gigara** [comment]
It works. Thanks
