### PR TITLE
Fix compilation error on master

### PR DESCRIPTION
**Pull request by Shadow-Devil**
## Purpose
Fix the compilation error introduced in #42854.
There, the JsonParser object was used, which was removed with #42945

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by Shadow-Devil** [comment]
@gimantha Could you please review and merge this PR before reviewing any of my other PRs please?
I fixed the compilation error introduced in #42854 
and also noticed that in #43067 I made a mistake for defining the output zip file.
This is now fixed, sorry for the inconvenience.

**Comment by gimantha** [comment]
> #42854

Sure.. but wondering where it was broken. I cannot see that the build is failing in the pointed PR. is it a regression issue not reflected in our tests?

**Comment by Shadow-Devil** [comment]
There should have been a merge conflict in #42854 but this wasn't detected by git. The pipeline ran with the previous version of master, where the `parser` variable was still defined.

**Comment by Shadow-Devil** [comment]
In summary: #42854 used a variable that was removed in #42945, but since the pipeline was running with the state of the branch, where the variable still existed there was no failure. This could have been prevented by either merging master into #42854 or rebasing it onto master.
The other issue with #43067 was not noticed because the successful build steps were cached. Once this cache expired and it was executed again it threw the build failure.

**Review by gimantha — APPROVED** [review]
