### ISSUE TITLE
[Bug]: nBallerina fails to compile with nutcracker branch

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#43288]
### Description

Current HEAD of nutcracker branch can't compile nBallerina and throws the fallowing error
```
ERROR [modules/print.llvm/llvm.bal:(1357:20,1357:43)] cannot infer type of the object from 'wso2/nballerina.print.llvm:0.1.0:Value'
ERROR [modules/print.llvm/llvm.bal:(1579:55,1579:57)] incompatible types: expected 'wso2/nballerina.print.llvm:0.1.0:StructType', found 'wso2/nballerina.print.llvm:0.1.0:(wso2/nballerina.print.llvm:0:$anonType$StructType$_0 & readonly)'
ERROR [modules/print.llvm/llvm.bal:(1636:92,1636:94)] incompatible types: expected 'wso2/nballerina.print.llvm:0.1.0:StructType', found 'wso2/nballerina.print.llvm:0.1.0:(wso2/nballerina.print.llvm:0:$anonType$StructType$_0 & readonly)'
ERROR [modules/print.llvm/llvm.bal:(1814:49,1814:59)] incompatible types: expected 'wso2/nballerina.print.llvm:0.1.0:StructType', found 'wso2/nballerina.print.llvm:0.1.0:(wso2/nballerina.print.llvm:0:$anonType$StructType$_0 & readonly)'
ERROR [modules/nback/init.bal:(669:42,669:52)] incompatible types: expected 'wso2/nballerina.print.llvm:0.1.0:StructType', found 'wso2/nballerina.print.llvm:0.1.0:(wso2/nballerina.print.llvm:0:$anonType$StructType$_0 & readonly)'
ERROR [modules/nback/init.bal:(670:86,670:96)] incompatible types: expected 'wso2/nballerina.print.llvm:0.1.0:StructType?', found 'wso2/nballerina.print.llvm:0.1.0:(wso2/nballerina.print.llvm:0:$anonType$StructType$_0 & readonly)'
...
```

Reverting 033de70 seems to fix the issue. But not sure if the bug was introduced by that or just uncovered with table changes.

### Related area

-> Compilation

**Comment by lochana-chathura** [comment]
Closing as this is fixed now
