### ISSUE TITLE
Query expression result in an unexpected runtime error 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#33709]
**Description:**
```ballerina
type BddPath record {|
    int[] pos = [1];
|};

public type MappingAlternative record {|
    int[] pos;
|};

public function main() {
    BddPath[] paths = [{}, {}, {}];

    MappingAlternative[] alts = from var {pos} in paths
        select {
            pos: (from var atom in pos
                select atom)
        };
}
```

```

error: {ballerina}TypeCastError {"message":"incompatible types: '()' cannot be cast to 'int'"}
        at ballerina.lang.query.0._SelectFunction:process(types.bal:590)
           ballerina.lang.query.0:$annon$method$delegate$0(types.bal:91)
           ballerina.lang.__internal.0:invokeAsExternal(stream-utils.bal:138)
           ballerina.lang.query.0._StreamPipeline:next(types.bal:91)
           ballerina.lang.query.0.IterHelper:next(types.bal:723)
           ballerina.lang.stream.0:next(stream.bal:67)
           ballerina.lang.query.0:toArray(helpers.bal:88)
           main:main(main.bal:12)
```

**Steps to reproduce:**

**Affected Versions:**
Beta-3
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
`null` is parsing to runtime type checker for sourceVal at  https://github.com/ballerina-platform/ballerina-lang/blob/6f684de69d218b7c731dd1230acfcb16a6500579/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java#L159

resulting in `"incompatible types: '()' cannot be cast to 'int'"`

**Comment by pcnfernando** [comment]
Should enable the specific test introduced in https://github.com/ballerina-platform/ballerina-lang/pull/35248/
