### ISSUE TITLE
system:exec() makes an internal conversion error in case of error

### ISSUE THREAD

**Issue by chipsmaster** [ballerina-platform/ballerina-lang#22491]
**Description:**

system:exec() makes a conversion error at runtime when the function fails and does not return one of the predefined errors, thus making the original error unavailable.
I think it happens for any error during the command invocation (ex: command does not exist) or during execution.
I have noticed the problem in 1.1.3 and still happens in 1.2

**Steps to reproduce:**

```
import ballerina/io;
import ballerina/system;


public function main() {
    io:println("start");
    system:Process|error p = system:exec("xxxxx");
    if (p is system:Process) {
        io:println("ok1");
        int|error status = p.waitForExit();
        if (status is int) {
            io:println("exit: " + status.toString());
            io:println("output:");
            io:println(readProcessOutputChannel(p.stdout()));
        } else {
            io:println("err waitForExit");
            io:println(status);
        }
    } else {
        io:println("err");
        io:println(p);
    }
    
    io:println("end");
}


function readProcessOutputChannel(io:ReadableByteChannel bc) returns string|error {
    string result = "";
    io:ReadableCharacterChannel textChannel = new(bc, "UTF-8");
    string|error readResult = "";
    while (!(readResult is io:EofError)) {
        readResult = textChannel.read(1000);
        if (readResult is string) {
            result += readResult;
        }
    }
    return result;
}
```

The output will be
```
start
error: {ballerina}TypeCastError message=incompatible types: 'error' cannot be cast to 'system:Process|system:InvalidOperationError|system:PermissionError|system:FileSystemError|system:FileNotFoundError'
	at ballerina:nativeExec(system.bal:85)
	   ballerina:exec(system.bal:82)
	   aaaa.xxxx:main(main.bal:78)

```

**Affected Versions:**

**OS, DB, other environment details and versions:**

debian buster, jdk8

**Comment by MaryamZi** [comment]
@chipsmaster this issue was reported recently (https://github.com/ballerina-platform/ballerina-lang/issues/22363) and was fixed for version 1.2.1 which is now available.

Could you please check with 1.2.1? You can use the `ballerina dist update` command to update to the latest patch version.

I tried the same and it worked as expected.

**Comment by chipsmaster** [comment]
It works in 1.2.1
