### ISSUE TITLE
Can't pass a string argument with spaces to the main function

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19547]
**Description:**
$title. 

This worked on 0.991.0. https://github.com/ballerina-platform/ballerina-lang/issues/2298 also used to work on 0.991.0 but doesn't work now - may have to recheck if something changed in how we use picocli with the jBallerina changes, to result in these issues. 
 
**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main(string s) {
    io:println(s);
}
```

```cmd
$ ballerina run xyz.bal "spaces here !"
Compiling source
        xyz.bal

Generating executables
Running executables

ballerina: too many arguments to call the 'main' function
```

**Affected Versions:**
1.0.1

**Comment by Kishanthan** [comment]
I checked with 1.0.3 build and it works fine.

```
➜  jballerina-1.0.3 ./bin/ballerina run foo.bal "this is a space"                                           
Compiling source
	foo.bal

Generating executables
Running executables

this is a space
```

**Comment by pubudu91** [comment]
I just checked this and it's not working for me either.

**Comment by Kishanthan** [comment]
Looks like a specific issue with picoli lib on linux machines
