### ISSUE TITLE
[Bug]: Duplicated error diagnostics for bala sources

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#39297]
### Description

Introduced by https://github.com/ballerina-platform/ballerina-lang/pull/35298

### Steps to Reproduce

Edit a bala source to have compilation errors and use it in a package.

**Output:**
ERROR [user/foo/0.2.0::foo.bal:(10:1,10:1)] missing semicolon token
ERROR [user/foo/0.2.0::foo.bal:(10:1,10:1)] missing semicolon token

### Affected Version(s)

At least 2201.3.0

### Related area

-> Compilation
