### ISSUE TITLE
Intermittent failure - ballerina-examples/fork-variable-access

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#13898]
**Description:**

```
Compiling source
    ballerina-examples/fork-variable-access:0.0.1

Running tests
    ballerina-examples/fork-variable-access:0.0.1
	[fail] testFunc:
	    error: {ballerina}TypeCastError {"message":"incompatible types: '()' cannot be cast to 'string'"}
	    	at ballerina-examples/fork-variable-access:0.0.1:main(fork_variable_access.bal:69)
	    	ballerina-examples/fork-variable-access:0.0.1:testFunc(tests/fork_variable_access_test.bal:26)

	0 passing
	1 failing
	0 skipped
```

**Comment by Shan1024** [comment]
Reopening since this is failed in https://github.com/ballerina-platform/ballerina-lang/pull/14047.

Complete log - [log-tests:fork_variable_access_test.txt](https://github.com/ballerina-platform/ballerina-lang/files/2921720/log-tests.fork_variable_access_test.txt)

**Comment by chamil321** [comment]
Failed in #14420
Log - [fork_variable_access_test.txt](https://github.com/ballerina-platform/ballerina-lang/files/2973409/14420.txt)
