### PR TITLE
[1.2.x] Fix `java.lang.NoClassDefFoundError` issue in openAPI validator

### PR DESCRIPTION
**Pull request by lnash94**
` java.lang.NoClassDefFoundError`  error was observed when building a project using Ballerina 1.2.25 release. The same code works in Ballerina 1.2.16. It happened due to a dependence version update.

Fixes [https://github.com/ballerina-platform/openapi-tools/issues/921](https://github.com/ballerina-platform/openapi-tools/issues/921)

 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: gradle/javaProject.gradle [hunk 1]
```diff
@@ -119,9 +119,9 @@ dependencies {
         implementation 'io.opentracing:opentracing-api:0.33.0'
         implementation 'io.opentracing:opentracing-util:0.33.0'
         implementation 'io.opentracing:opentracing-mock:0.33.0'
-        implementation 'io.swagger.core.v3:swagger-models:1.5.18'
-        implementation 'io.swagger.parser.v3:swagger-parser:2.0.14'
-        implementation 'io.swagger.parser.v3:swagger-parser-v2-converter:2.0.14'
+        implementation "io.swagger.core.v3:swagger-models:2.1.11"
+        implementation "io.swagger.parser.v3:swagger-parser-v2-converter:2.0.28"
+        implementation "io.swagger.parser.v3:swagger-parser:2.0.28"
```
Comment (NipunaRanasinghe) [inline gradle/javaProject.gradle:124]: Shall we use single quotes in here, to be consistent with the rest of the entries?

**Review by NipunaRanasinghe — APPROVED** [review]
