### ISSUE TITLE
Enable failing ModuleExecutionFlowTests

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#30005]
**Description:**
Enable failing ModuleExecutionFlowTests disabled in https://github.com/ballerina-platform/ballerina-lang/pull/30004

**Describe your task(s)**

**Comment by rdhananjaya** [comment]
There seems to be refactoring after disabling this test cases.
I get below error when I re-enabled the test.
```log
Exception in thread "Thread-1" java.lang.NoSuchMethodError: io.ballerina.runtime.internal.util.RuntimeUtils.handleRuntimeErrors(Ljava/lang/Throwable;)V
 -         at unit_tests.proj6.0_1_0.$_init.$moduleStop(proj6)
 -         at unit_tests.proj6.0_1_0.$_init$Signa
 ```
